Removed Authors from domains
utopia-php/domains pull request #20
Opened 2022-10-13 07:04 UTC by Aishubalaji

2022-10-13 08:04 UTC, Meldiron commented
Linking issue: https://github.com/appwrite/appwrite/issues/4415

2022-10-13 08:05 UTC, Meldiron requested changes
One tiny comment 🤏 I can mark as approved once resolved.

2022-10-13 08:05 UTC, Meldiron commented on tests/DomainTest.php
> - * @author Eldad Fux <eldad@appwrite.io>
Let's remove the whole comment blocks, please.

2022-10-17 05:23 UTC, Aishubalaji commented
@Meldiron can you review this?

2022-12-06 06:12 UTC, closed without merging