Added code linter
utopia-php/domains pull request #21
Opened 2022-10-13 09:18 UTC by neelshah2409

Added the linter.yml in workflows and updated the composer.

2022-10-14 10:24 UTC, neelshah2409 commented
@Meldiron please review it and the data.php thing once again prompted automatically so please see it .

2022-10-17 07:17 UTC, Meldiron commented
@neelshah2409 I see, looks like automation is doing these changes. Let's ignore those.

2022-10-17 07:27 UTC, Meldiron requested changes

2022-10-17 07:27 UTC, Meldiron commented on composer.json
> +        "phpstan/phpstan": "1.9.x-dev"
Wrong dependency. Linter uses `pint`, not `phpstan`. Let's switch that.

2022-10-17 09:45 UTC, neelshah2409 commented on composer.json
> +        "phpstan/phpstan": "1.9.x-dev"
@Meldiron changes are done please review it .

2022-10-17 11:14 UTC, Meldiron approved these changes
Looks great 🎉

2022-12-20 22:48 UTC, christyjacob4 commented
@neelshah2409 please resolve the merge conflicts

2023-01-27 21:50 UTC, merged

2023-01-27 21:50 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)