Add support for wildcard and exception
utopia-php/domains pull request #29
Opened 2023-04-12 04:41 UTC by Suven-p

Fix #22 
Fix https://github.com/appwrite/appwrite/issues/5317 

Appwrite relies on [public suffix list](https://github.com/publicsuffix/list) to parse domain names. According to the [format specification](https://github.com/publicsuffix/list/wiki/Format):
1. The wildcard character * matches any valid sequence of characters in a hostname part.
2. An exclamation mark (!) at the start of a rule marks an exception to a previous wildcard rule. An exception rule takes priority over any other matching rule.

Current behaviour:
The current implementation does not handle both cases. It handles suffixes without * and ! which covers all common use cases but excludes some country tld's such as *.np.

Expected behaviour:
- With rule: *.np suffix for example.com.np is com.np
- With rules: *.kawasaki.jp and !city.kawasaki.jp suffix for app.example.kawasaki.jp is example.kawasaki.jp and suffix for app.city.kawasaki.jp is kawasaki.jp

2023-04-13 09:56 UTC, Suven-p commented
@TorstenDittmann Could you please review this?

2023-04-19 04:51 UTC, Suven-p commented
@wess Could you review this 😅? I can't currently use my domain since it's not supported https://github.com/appwrite/appwrite/issues/5317

2023-04-19 13:57 UTC, wess commented
Could you please add a test (or 2) for testing the rules?

2023-04-19 14:47 UTC, Suven-p commented
> Did you pull in the latest master? There was an issue with that test but it should be addressed.

I think so. The hash of third last commit from my branch matches with master.

2023-04-19 15:51 UTC, wess commented
> > Did you pull in the latest master? There was an issue with that test but it should be addressed.
> 
> I think so. The hash of third last commit from my branch matches with master.

Thank you for checking, if you could add those tests then i can also run the tests to see if there is any branch drift. Thanks again for the contribution, this is a killer feature.

2023-04-19 16:06 UTC, Suven-p commented
The last commit adds the tests.

2023-04-27 13:40 UTC, Suven-p commented
@wess Any updates?

2023-04-27 18:14 UTC, Meldiron commented on tests/DomainTest.php
> +        $this->assertEquals('', $domain->getSub());
Isnt subdomain supposed to be `example` here?

2023-04-27 18:20 UTC, Meldiron approved these changes

2023-05-04 16:26 UTC, stnguyen90 commented
@wess, should the travis build pass?

2023-05-16 20:04 UTC, wess reviewed
Looks good, and no issues on my end. @TorstenDittmann should this type of update be required to pass Travis?

2023-05-16 20:04 UTC, wess reviewed
Looks good, and no issues on my end. @TorstenDittmann should this type of update be required to pass Travis?

2023-07-19 15:46 UTC, stnguyen90 requested changes
Would you be able to add some additional test cases?

- *.nom.br
- *.kawasaki.jp
- !city.kawasaki.jp
- *.dev.adobeaemcloud.com
- adobeaemcloud.net

2023-07-19 16:28 UTC, stnguyen90 approved these changes
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

2023-07-19 16:39 UTC, merged